server:
  port: 8277

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lease?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false
    username: 'root'
    password: '@#root@#'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB




#   Email Configurations
  mail:
    host: 10.95.110.23
    port: 25
    username: contractmanagement@netone.co.zw
    password: '!@Cm_2025!@'
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: flase





#Notifier Configurations
notification:
  email: smtasa@netone.co.zw
  interval: 6
  cron_expiring_soon: '0 */3 * * * *'
  #  cron_expiring_soon: '* * * 1 * *'


  ## Contract Viewing URL
contract:
  view:
    url: http://10.95.10.139:3007

secret:
  key: 38EA0125C0F8C5DF8C5EABB1A834A88F5974D69839E02CABDC359F1BEAE4709B4DE5EE149463F86984A0F34CE6AD83E9313201CF2810208674E14D3A71FB16DF

#Active Directory Configurations
active.directory:
  domain: 'netone.co.zw'
  url: 'ldap://10.95.10.63:389'
  root_dn: 'dc=netone,dc=co,dc=zw'


file:
  upload:
    path: C:\Users\user\Desktop\MyFiles

logging:
  level:
    org:
      springframework:
        web:
          multipart: DEBUG
